---
title: "https://github.com/bearloga/bayesopt-tutorial-r/blob/master/index.Rmd"
output: html_notebook
---

```{r packages}
library(tidyverse)
library(gt)
library(GPfit)
library(BASS)

library(lhs)
library(plotly)
```

```{r function, echo=TRUE}
f <- function(x1,x2) {
  y1 <- x1 * 2 + 0.5
  y2 <- x2 * 2 + 0.5
  return((sin(10 * pi * y1)/(2 * y2) + (y1-1)^4))
}
```

```{r}
n0 = 20
XX <- maximinLHS(30, 2)
Y <- f(XX[,1], XX[,2])
```

```{r}
fit <- bass(XX,Y, verbose = FALSE)
```

```{r}
plot(fit)
```


# Iterative run

```{r}
max_iterations = 100

n0 <- 15
dims <- 2
XX <- maximinLHS(n0, dims)
Y <- f(XX[,1], XX[,2])

for (iteration in 1:max_iterations) {

  fit <- bass(
    xx = XX,
    y = Y,
    degree = 1,
    verbose = F,
    nmcmc = 600,
    nburn=300,
    #thin = 10
    )

  x_new <- maximinLHS(1000,dims)
  pred <- predict(fit, newdata = data.frame(x = x_new))
  mu <- apply(pred,2,mean)
  
  kappa <- 9 # tunable
  sigma <- apply(pred,2,sd)
  lower_confidence_bound <- mu - kappa * sigma
  
  XX <- rbind(XX, x_new[which.min(lower_confidence_bound),])
  Y <- append(Y, f(x_new[which.min(lower_confidence_bound),][1],x_new[which.min(lower_confidence_bound),][2]))

}
```

```{r}
fig <- plot_ly(x = XX[,1], y = XX[,2], z = Y, type = 'scatter3d', mode = 'markers')
fig
```

```{r}
plotting <- maximinLHS(2000,2)

fig <- plot_ly(x = plotting[,1], 
               y = plotting[,2], 
               z = f(plotting[,1], plotting[,2]), 
               intensity = ~f(plotting[,1], plotting[,2]),
               colors = colorRamp(c("blue", "green", "yellow")),
               type = 'mesh3d')
fig
```

```{r}
plotting <- maximinLHS(2000,2)

fig <- plot_ly() |> 
  add_mesh(x = plotting[,1], 
               y = plotting[,2], 
               z = f(plotting[,1], plotting[,2]), 
               intensity = ~f(plotting[,1], plotting[,2]),
               colors = colorRamp(c("blue", "green", "yellow")),
               type = 'mesh3d') |> 
  add_markers(x = XX[,1], y = XX[,2], z = Y, color = '#BF382A')
fig
```

```

