---
title: "BASS Testing"
author: "ATJ"
date: "2022-08-06"
output: html_document
---

```{r packages}
library(tidyverse)
library(gt)
library(GPfit)
library(BASS)
library(lhs)
library(plotly)
```

```{r function, echo=TRUE}
f <- function(x1,x2) {
  y1 <- x1 * 2 + 0.5
  y2 <- x2 * 2 + 0.5
  return((sin(10 * pi * y1)/(2 * y2) + (y1-1)^4))
}
```

```{r Branin-Hoo, echo=TRUE}
f <- function(x1,x2) {
  y1 <- x1 * 15
  y2 <- x2 * 20 - 5
  a <- 1
  b <- 5.1 / (4 * pi ^2)
  c <- 5 / pi
  r <- 6
  s <- 10
  t <- 1 / (8 * pi)
  return(a * (y2 - b * y1^2 + c * y1 - r)^2 + s * (1-t) * cos(y1) + s)
}
```

```{r}
n0 = 20
XX <- maximinLHS(30, 2)
Y <- f(XX[,1], XX[,2])
```

```{r}
fit <- bass(XX,Y, verbose = FALSE)
```

```{r}
plot(fit)
```


```{r}
get_bass_2d <- function(max_iterations = 100){
n0 <- 10
dims <- 2
XX <- maximinLHS(n0, dims)
Y <- f(XX[,1], XX[,2])

for (iteration in 1:max_iterations) {

  fit <- bass(
    xx = XX,
    y = Y,
    degree = 1,
    verbose = F,
    #nmcmc = 600,
    #nburn=300,
    #thin = 10
    )

  x_new <- maximinLHS(1000,dims)
  pred <- predict(fit, newdata = data.frame(x = x_new))
  mu <- apply(pred,2,mean)
  
  kappa <- 9 # tunable
  sigma <- apply(pred,2,sd)
  lower_confidence_bound <- mu - kappa * sigma
  
  XX <- rbind(XX, x_new[which.min(lower_confidence_bound),])
  Y <- append(Y, f(x_new[which.min(lower_confidence_bound),][1],x_new[which.min(lower_confidence_bound),][2]))

}
  
  return(Y)
}
```

```{r}
get_bass_2d(max_iterations = 10)
```

```{r}
results <- replicate(10, get_bass_2d(max_iterations = 100), simplify="array")
```

```{r}
results
```











