#!/usr/bin/env python3
"""Phase 0 of the writing plan: generate numbers.md, the canonical extract
of final_results/ (the thesis's versioned final protocol run). Deterministic:
re-running on the same inputs reproduces the file byte-for-byte.

Every thesis-derived statistic the article quotes must appear here first.
New (article-loop) experimental numbers are canonical in their experiment's
ANALYSIS.md instead, and are NOT duplicated here.
"""
import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
FR = REPO / "final_results"
OUT = Path(__file__).resolve().parents[1] / "numbers.md"

ORDER = ["branin", "rastrigin", "synthetic", "func2C", "func3C",
         "cat_ackley_d3_L5", "cat_ackley_d4_L7", "cat_ackley_d6_L11",
         "nlp_hpo"]


def read(path):
    with path.open() as fh:
        return list(csv.DictReader(fh))


def fmt(x, nd=4):
    return f"{float(x):.{nd}g}"


def _isfloat(s):
    try:
        float(s)
        return True
    except ValueError:
        return False


lines = [
    "# numbers.md — canonical thesis-run numbers for the article",
    "",
    "Generated by `tools/extract_numbers.py` from `final_results/` (final",
    "protocol: budget 80, 25 seeds 1001–1025; see final_results/README.md).",
    "Do not edit by hand — regenerate. Article text may only quote",
    "thesis-derived statistics that appear here; numbers from the article's",
    "own experiments are canonical in their `article_loop/experiments/*/`",
    "ANALYSIS.md files.",
    "",
]

for bench in ORDER:
    d = FR / bench
    if not d.is_dir():
        continue
    lines.append(f"## {bench}")
    lines.append("")
    fs = read(d / "final_summary.csv")
    lines.append("| method | mean final | sd |")
    lines.append("|---|---|---|")
    for r in fs:
        lines.append(f"| {r['method']} | {fmt(r['mean_final'])} | {fmt(r['sd_final'])} |")
    pv = d / "paired_vs_random.csv"
    if pv.exists():
        lines.append("")
        lines.append("| method vs Random | W/T/L (n) | median (method / Random) | Wilcoxon p |")
        lines.append("|---|---|---|---|")
        for r in read(pv):
            lines.append(
                f"| {r['method']} | {r['wins']}/{r['ties']}/{r['losses']} ({r['n_seeds']}) "
                f"| {fmt(r['median_final'])} / {fmt(r['median_baseline'])} "
                f"| {fmt(r['p_wilcoxon'], 3)} |")
    lines.append("")

# Elastic net has a different file set
en = FR / "elastic_net"
if en.is_dir():
    lines.append("## elastic_net (case study; its own defaults)")
    lines.append("")
    fs = en / "final_summary_cv.csv"
    if fs.exists():
        rows = read(fs)
        cols = list(rows[0].keys())
        lines.append("| " + " | ".join(cols) + " |")
        lines.append("|" + "---|" * len(cols))
        for r in rows:
            lines.append("| " + " | ".join(
                fmt(r[c]) if _isfloat(r[c]) else r[c] for c in cols) + " |")
    tr = en / "test_rmse_summary.csv"
    if tr.exists():
        lines.append("")
        rows = read(tr)
        cols = list(rows[0].keys())
        lines.append("| " + " | ".join(cols) + " |")
        lines.append("|" + "---|" * len(cols))
        for r in rows:
            lines.append("| " + " | ".join(
                fmt(r[c]) if _isfloat(r[c]) else r[c] for c in cols) + " |")
    lines.append("")

lines += [
    "## Fixed reference values (from the article loop, cross-referenced)",
    "",
    "- Exact optima (E1, analytically proven in review): func2C **−0.206326**",
    "  at combo (2,2); func3C **−0.722140** at combo (2,2,1). Cat-Ackley",
    "  optimum 0 by construction.",
    "- The scaffold figure \"−0.148 at budget 10\" is refuted as recorded",
    "  (E1/E2 + R re-check) and must not be quoted.",
    "",
]

text = "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
