#!/usr/bin/env python3
"""Generate h_numbers.md — the canonical headline-experiment numbers the
article may quote (same hygiene rule as writing_loop/numbers.md). Reads
exph1_matrix/results.jsonl, exph2_control/results.jsonl and the H3 fit
table; recomputes everything from raw rows (no trust in ANALYSIS prose)."""
import json
import math
from collections import defaultdict
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
HU = HERE.parent
BUDGET = 80
K = {"cat_ackley_d3_L5": 125, "cat_ackley_d5_L5": 3125,
     "cat_ackley_d6_L11": 11 ** 6, "pest_control": 5 ** 25,
     "func2C": None, "func3C": None}
SOLVE = {"cat_ackley_d3_L5": 1e-9, "cat_ackley_d5_L5": 1e-9,
         "func2C": -0.206326 + 1e-3, "func3C": -0.722140 + 1e-3}
LIBS = ["random", "optuna-tpe", "hyperopt-tpe", "optuna-gp", "skopt-gp", "ax", "smac"]
BENCH = ["cat_ackley_d3_L5", "cat_ackley_d5_L5", "cat_ackley_d6_L11",
         "pest_control", "func2C", "func3C"]


def pigeonhole(k, b=BUDGET):
    if k is None:
        return 0.0
    return max(0.0, b + k * math.expm1(b * math.log1p(-1.0 / k)))


def load(p):
    cells = defaultdict(list)
    for line in Path(p).read_text().splitlines():
        r = json.loads(line)
        cells[(r["library"], r["benchmark"])].append(r)
    return cells


def main():
    h1 = load(HU / "exph1_matrix" / "results.jsonl")
    h2 = load(HU / "exph2_control" / "results.jsonl")

    out = ["# h_numbers.md — canonical headline-experiment numbers",
           "", "Generated by tools/extract_h_numbers.py from raw results.jsonl;",
           "do not edit by hand. Article H-claims quote ONLY from here.", ""]

    out += ["## H1 as-shipped audit (7 libs x 6 benchmarks x 25 seeds, budget 80)", "",
            "| library | benchmark | med revisits | mean | med excess | med best | solved | version |",
            "|---|---|---|---|---|---|---|---|"]
    versions = {}
    for lib in LIBS:
        for b in BENCH:
            rs = h1.get((lib, b), [])
            if not rs:
                continue
            rev = [r["revisits"] for r in rs]
            best = [r["best"] for r in rs]
            ph = pigeonhole(K[b])
            thr = SOLVE.get(b)
            sv = "n/a" if thr is None else f"{sum(x <= thr for x in best)}/{len(rs)}"
            ver = next((r.get("version") for r in rs if r.get("version") not in (None, "-")), "-")
            versions[lib] = ver
            out.append(f"| {lib} | {b} | {np.median(rev):.0f} | {np.mean(rev):.1f} "
                       f"| {np.median(rev)-ph:+.1f} | {np.median(best):.4g} | {sv} | {ver} |")

    # headline X/N
    purecat = BENCH[:4]
    out += ["", "## Headline X/N (excess as % of budget, >=1 pure-cat benchmark)", ""]
    N = len(LIBS) - 1
    for y in (10, 25, 40):
        xs = []
        for lib in LIBS:
            if lib == "random":
                continue
            worst = max((np.median([r["revisits"] for r in h1[(lib, b)]]) - pigeonhole(K[b]))
                        / BUDGET * 100 for b in purecat if h1.get((lib, b)))
            if worst >= y:
                xs.append(lib)
        out.append(f"- excess >= {y}%: **{len(xs)}/{N}** ({', '.join(xs) or 'none'})")

    og = h1[("optuna-gp", "cat_ackley_d3_L5")]
    out += ["", "## H1-MASK key numbers (optuna-gp on cat_ackley_d3_L5)", "",
            f"- median revisits {np.median([r['revisits'] for r in og]):.0f}/80; "
            f"range {min(r['revisits'] for r in og)}-{max(r['revisits'] for r in og)}; "
            f"median unique {np.median([r['unique'] for r in og]):.0f} "
            f"(range {min(r['unique'] for r in og)}-{max(r['unique'] for r in og)}); "
            f"solved {sum(r['best'] <= 1e-9 for r in og)}/25"]
    d6 = h1[("optuna-gp", "cat_ackley_d6_L11")]
    out.append(f"- optuna-gp exact solves on d6_L11 (K=1{','}771{','}561): "
               f"{sum(r['best'] <= 1e-9 for r in d6)}/25; ax {sum(r['best'] <= 1e-9 for r in h1[('ax','cat_ackley_d6_L11')])}/25; all others 0/25")
    smac_rows = [r for (l, b), rs in h1.items() if l == "smac" for r in rs]
    out.append(f"- smac total revisits across all {len(smac_rows)} runs: "
               f"{sum(r['revisits'] for r in smac_rows)}; early terminations "
               f"{sum(1 for r in smac_rows if r.get('early_termination'))} "
               f"(evals {sorted(r['evals'] for r in smac_rows if r.get('early_termination'))})")
    mixed = [r for (l, b), rs in h1.items() if b in ("func2C", "func3C") for r in rs]
    nz = [(l, b, r["seed"], r["revisits"]) for (l, b), rs in h1.items()
          if b in ("func2C", "func3C") for r in rs if r["revisits"] > 0]
    out.append(f"- mixed-space runs with 0 revisits: {sum(1 for r in mixed if r['revisits']==0)}/{len(mixed)}; nonzero: {nz}")

    # H2
    out += ["", "## H2 budget-equalized (memoized) key numbers", ""]
    for lib, b in (("optuna-tpe", "cat_ackley_d5_L5"), ("optuna-tpe", "cat_ackley_d3_L5"),
                   ("hyperopt-tpe", "cat_ackley_d5_L5"), ("optuna-gp", "cat_ackley_d3_L5"),
                   ("optuna-gp", "cat_ackley_d5_L5"), ("hyperopt-tpe", "cat_ackley_d6_L11"),
                   ("optuna-tpe", "cat_ackley_d6_L11")):
        rs1, rs2 = h1.get((lib, b), []), h2.get((lib, b), [])
        if not rs2:
            continue
        thr = SOLVE.get(b)
        s1 = "n/a" if thr is None else f"{sum(r['best'] <= thr for r in rs1)}/25"
        s2 = "n/a" if thr is None else f"{sum(r['best'] <= thr for r in rs2)}/25"
        out.append(f"- {lib} @ {b}: med best {np.median([r['best'] for r in rs1]):.4g} -> "
                   f"{np.median([r['best'] for r in rs2]):.4g}; solves {s1} -> {s2}; "
                   f"med unique/proposals {np.median([r['unique_evals_charged'] for r in rs2]):.0f}/"
                   f"{np.median([r['proposals'] for r in rs2]):.0f}")
    out.append("- Z-of-W (registered metric: median best + solve-count tie-break, tol 1e-9): "
               "**Z = 3 of 4** (d3_L5, d5_L5, d6_L11 change; pest unchanged) — from analyze_h2.py post-Amendment-2")

    # H3
    fit = (HU / "h3_theory" / "fit_results.md").read_text()
    out += ["", "## H3 decay fit (verbatim from fit_results.md)", ""] + fit.splitlines()[2:]

    out += ["", "## Run counts and library versions", "",
            f"- H1: {sum(len(v) for v in h1.values())} runs; H2: {sum(len(v) for v in h2.values())} runs; "
            "H0 gates: G1-G4 + D1-D4 (40 library runs + scripted/analytic checks); H2 gate G5.",
            f"- Versions: {json.dumps(versions)}"]

    (HERE / "h_numbers.md").write_text("\n".join(out) + "\n")
    print(f"wrote h_numbers.md ({len(out)} lines)")


if __name__ == "__main__":
    main()
