---
title: "BASS Testing"
author: "ATJ"
date: "2022-08-06"
output: html_document
---

```{r}
library(ggplot2)
```

```{r}
results <- scan(file = "Branin-Hoo_Results_BASS_100k.txt")
results <- matrix(results, ncol = 100, byrow = TRUE)

Group <- 1:100
Mean <- apply(results[11:110,], 1, mean)
SD <- apply(results[11:110,], 1, sd) 
df <- data.frame(Group,Mean,SD)
```

```{r}
ggplot(data=df, aes(x=Group, y=Mean, group=1)) +
  geom_errorbar(aes(ymin=Mean-SD, ymax=Mean+SD), width=.1) +
  geom_line()+
  geom_point()
```


```{r}
tpe <- read.csv(file = 'TPE_hyperopt_100x100.csv')


Group <- 1:100
Mean <- apply(tpe, 1, mean)
SD <- apply(tpe, 1, sd) 
df_tpe <- data.frame(Group,Mean,SD)

ggplot(data=df, aes(x=Group, y=Mean, group=1)) +
  geom_errorbar(aes(ymin=Mean-SD, ymax=Mean+SD)) +
  geom_line()+
  geom_point() + 
  geom_line(data = df_tpe,aes(x=Group,y=Mean),colour="red")+
  geom_point(data = df_tpe,aes(x=Group,y=Mean),colour="red") + 
  geom_errorbar(data=df_tpe,aes(ymin=Mean-SD,ymax=Mean+SD),colour="red")


```

```{r}
gp <- read.csv(file = 'GP_hyperopt_Branin.csv')
gp <- t(gp)

Group <- 1:100
Mean <- apply(gp[11:110,], 1, mean)
SD <- apply(gp[11:110,], 1, sd) 
gp_df <- data.frame(Group,Mean,SD)

ggplot(data=df, aes(x=Group, y=Mean, group=1)) +
  geom_errorbar(aes(ymin=Mean-SD, ymax=Mean+SD)) +
  geom_line()+
  geom_point() + 
  geom_line(data = df_tpe,aes(x=Group,y=Mean),colour="red")+
  geom_point(data = df_tpe,aes(x=Group,y=Mean),colour="red") + 
  geom_errorbar(data=df_tpe,aes(ymin=Mean-SD,ymax=Mean+SD),colour="red") + 
  geom_line(data = gp_df,aes(x=Group,y=Mean),colour="blue")+
  geom_point(data = gp_df,aes(x=Group,y=Mean),colour="blue") + 
  geom_errorbar(data=gp_df,aes(ymin=Mean-SD,ymax=Mean+SD),colour="blue")
```



