---
title: "https://github.com/bearloga/bayesopt-tutorial-r/blob/master/index.Rmd"
output: html_notebook
---

```{r packages}
library(purrr)
library(gt)
library(GPfit)

f <- function(x) {
  return((6 * x - 2)^2 * sin(12 * x - 4))
}
```

```{r}
# seed with a few evaluations:
n0 <- 8
evaluations <- matrix(
  as.numeric(NA),
  ncol = 2, nrow = n0,
  dimnames = list(NULL, c("x", "y"))
)
evaluations[, "x"] <- seq(0, 1, length.out = n0)
evaluations[, "y"] <- f(evaluations[, "x"])
```

```{r}
fit <- GP_fit(
  X = evaluations[, "x"],
  Y = evaluations[, "y"],
  corr = list(type = "exponential", power = 1.95)
)

x_new <- seq(0, 1, length.out = 1000)
pred <- predict.GP(fit, xnew = data.frame(x = x_new))
mu <- pred$Y_hat
sigma <- sqrt(pred$MSE)

kappa <- 20 # tunable
lower_confidence_bound <- mu - kappa * sigma

evaluations <- rbind(evaluations,c(x_new[which.min(lower_confidence_bound)] , f(x_new[which.min(lower_confidence_bound)])))


evaluations # <- evaluations[order(evaluations[,"x"]),]
```





```{r, fig.width=8, fig.height=4}
plot_posterior <- function() {
  plot(
    x_new, mu,
    type = "l", col = "blue", lwd = 2, lty = "dotted",
    ylim = c(-10, 20),
    xlab = "x", ylab = "f(x)", main = "Posterior of f"
  )
  polygon(
    c(x_new, rev(x_new)),
    c(mu + sigma, rev(mu - sigma)),
    col = rgb(0, 0, 1, 0.25), border = NA
  )
  points(evaluations, pch = 16)
  legend(
    "topleft",
    c(expression(f[n[0]]), expression(mu(x)), expression(mu(x) %+-% sigma(x))),
    col = c("black", "blue", "blue"), pch = c(16, NA, NA),
    lty = c(NA, "dotted", NA), lwd = c(NA, 2, 1), bty = "n",
    fill = c(NA, NA, rgb(0, 0, 1, 0.25)),
    border = c(NA, NA, NA), ncol = 3, text.width = 0.1
  )
}
par(cex = 1.1, mfrow = c(1, 1), mar = c(5.1, 4.1, 4.1, 2.1))
plot_posterior()
```















```{r}
max_iterations = 20

f <- function(x) {
  return((6 * x - 2)^2 * sin(12 * x - 4))
}

# seed with a few evaluations:
n0 <- 4
evaluations <- matrix(
  as.numeric(NA),
  ncol = 2, nrow = n0,
  dimnames = list(NULL, c("x", "y"))
)
evaluations[, "x"] <- seq(0, 1, length.out = n0)
evaluations[, "y"] <- f(evaluations[, "x"])

for (iteration in 1:max_iterations) {

fit <- GP_fit(
      X = evaluations[, "x"],
      Y = evaluations[, "y"],
      corr = list(type = "exponential", power = 1.95)
      )

x_new <- seq(0, 1, length.out = 1000)
pred <- predict.GP(fit, xnew = data.frame(x = x_new))
mu <- pred$Y_hat
sigma <- sqrt(pred$MSE)
kappa <- 20 # tunable
lower_confidence_bound <- mu - kappa * sigma

evaluations <- rbind(evaluations,c(x_new[which.min(lower_confidence_bound)] , f(x_new[which.min(lower_confidence_bound)])))
}

evaluations
```

















